In [1]:
import os
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Using TensorFlow backend.
c:\users\vishesh jain\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\vishesh jain\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\vishesh jain\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype

In [2]:
data = pd.read_csv('data/reliance.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5141 entries, 0 to 5140
Data columns (total 15 columns):
Date                  5141 non-null object
Symbol                5141 non-null object
Series                5141 non-null object
Prev Close            5141 non-null float64
Open                  5141 non-null float64
High                  5141 non-null float64
Low                   5141 non-null float64
Last                  5141 non-null float64
Close                 5141 non-null float64
VWAP                  5141 non-null float64
Volume                5141 non-null int64
Turnover              5141 non-null float64
Trades                2291 non-null float64
Deliverable Volume    4627 non-null float64
%Deliverble           4627 non-null float64
dtypes: float64(11), int64(1), object(3)
memory usage: 602.6+ KB


In [6]:
data.describe()

Prev Close         Open         High          Low         Last  \
count  5141.000000  5141.000000  5141.000000  5141.000000  5141.000000   
mean    977.737065   979.234332   993.166077   963.957294   977.921659   
std     548.187888   549.657568   559.194988   537.759371   548.159898   
min     203.200000   205.500000   219.500000   197.150000   203.300000   
25%     556.050000   559.100000   568.600000   550.000000   557.550000   
50%     923.750000   925.700000   936.650000   915.100000   923.900000   
75%    1171.750000  1176.550000  1198.250000  1152.300000  1175.400000   
max    3220.850000  3298.000000  3298.000000  3141.300000  3223.000000   

             Close         VWAP        Volume      Turnover        Trades  \
count  5141.000000  5141.000000  5.141000e+03  5.141000e+03  2.291000e+03   
mean    978.096460   978.644639  5.336247e+06  5.398477e+14  1.310276e+05   
std     548.305224   548.351897  4.674347e+06  7.033455e+14  1.131774e+05   
min     203.200000   212.290000  5.282000e+04  4.295543e+12  2.991000e+03   
25%     556.250000   557.510000  2.801842e+06  2.160521e+14  7.061900e+04   
50%     924.100000   925.730000  4.129033e+06  3.557919e+14  9.688100e+04   
75%    1174.050000  1174.130000  6.335308e+06  6.248018e+14  1.491880e+05   
max    3220.850000  3197.750000  6.523089e+07  1.236080e+16  1.285533e+06   

       Deliverable Volume  %Deliverble  
count        4.627000e+03  4627.000000  
mean         2.206850e+06     0.438410  
std          1.827142e+06     0.145129  
min          2.909700e+04     0.076300  
25%          1.168824e+06     0.327050  
50%          1.765227e+06     0.455100  
75%          2.640922e+06     0.547300  
max          3.495888e+07     0.978300

In [7]:
data.head(n=10)

Date    Symbol Series  Prev Close    Open    High     Low    Last  \
0  2000-01-03  RELIANCE     EQ      233.05  237.50  251.70  237.50  251.70   
1  2000-01-04  RELIANCE     EQ      251.70  258.40  271.85  251.30  271.85   
2  2000-01-05  RELIANCE     EQ      271.85  256.65  287.90  256.65  286.75   
3  2000-01-06  RELIANCE     EQ      282.50  289.00  300.70  289.00  293.50   
4  2000-01-07  RELIANCE     EQ      294.35  295.00  317.90  293.00  314.50   
5  2000-01-10  RELIANCE     EQ      314.55  317.40  318.70  305.30  306.65   
6  2000-01-11  RELIANCE     EQ      308.50  307.95  310.95  283.85  288.50   
7  2000-01-12  RELIANCE     EQ      288.50  289.00  305.00  282.15  304.70   
8  2000-01-13  RELIANCE     EQ      301.70  306.00  316.40  304.10  309.75   
9  2000-01-14  RELIANCE     EQ      311.85  309.50  321.65  309.50  317.00   

    Close    VWAP    Volume      Turnover  Trades  Deliverable Volume  \
0  251.70  249.37   4456424  1.111319e+14     NaN                 NaN   
1  271.85  263.52   9487878  2.500222e+14     NaN                 NaN   
2  282.50  274.79  26833684  7.373697e+14     NaN                 NaN   
3  294.35  295.45  15682286  4.633254e+14     NaN                 NaN   
4  314.55  308.91  19870977  6.138388e+14     NaN                 NaN   
5  308.50  312.35  13417057  4.190855e+14     NaN                 NaN   
6  288.50  296.40  12544322  3.718192e+14     NaN                 NaN   
7  301.70  294.57  12109507  3.567081e+14     NaN                 NaN   
8  311.85  311.79  17076042  5.324181e+14     NaN                 NaN   
9  316.30  316.17  13460592  4.255879e+14     NaN                 NaN   

   %Deliverble  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          NaN  
9          NaN

In [9]:
print(data.columns)

Index(['Date', 'Symbol', 'Series', 'Prev Close', 'Open', 'High', 'Low', 'Last',
       'Close', 'VWAP', 'Volume', 'Turnover', 'Trades', 'Deliverable Volume',
       '%Deliverble'],
      dtype='object')


In [10]:
features_to_drop = ['Date', 'Symbol', 'Series', 'Prev Close', 'Last', 'VWAP', 'Volume', 'Turnover', 'Trades', 'Deliverable Volume',
                       '%Deliverble']

In [11]:
data = data.drop(columns=features_to_drop)

In [12]:
data.head(n=10)

Open    High     Low   Close
0  237.50  251.70  237.50  251.70
1  258.40  271.85  251.30  271.85
2  256.65  287.90  256.65  282.50
3  289.00  300.70  289.00  294.35
4  295.00  317.90  293.00  314.55
5  317.40  318.70  305.30  308.50
6  307.95  310.95  283.85  288.50
7  289.00  305.00  282.15  301.70
8  306.00  316.40  304.10  311.85
9  309.50  321.65  309.50  316.30

In [13]:
## we have to normailize close but at the time of prediction we should have denomalized output

X = data.values
mean = np.mean(X , axis =0)
std = np.std(X , axis =0)

In [16]:
print(mean)

[979.23433184 993.16607664 963.9572943  978.09645983]


In [17]:
print(std)

[549.60410704 559.14059906 537.7070675  548.25189454]


In [18]:
X =( X - mean )/std

In [19]:
print( np.mean(X , axis=0))

[ 2.21137595e-16  2.21137595e-17  1.87966956e-16 -2.21137595e-17]


In [20]:
print( np.std(X , axis=0))

[1. 1. 1. 1.]


In [21]:
## for rnn model we need data in form of  sequence 
## here we are deciding to take sequence length of 10 and 11th will be the prediction

Sequence_length = 11


In [22]:
data_x = []
data_y = []


for i in range(len(X) - Sequence_length ):
    window = X[i:i+Sequence_length]
    x = window[:-1] 
    y = window[-1, [0]] 

    data_x.append(x)
    data_y.append(y)
    


In [23]:
X_sequence =np.array( data_x[:-1])

In [24]:
Y =np.array( data_y)

In [32]:
print(X_sequence.shape)

(5129, 10, 4)


In [33]:
print(len(Y))

5130


In [31]:
print(X_sequence[0])

[[-1.34957931 -1.32608163 -1.35102798 -1.32493196]
 [-1.31155194 -1.29004418 -1.32536345 -1.28817879]
 [-1.31473605 -1.26133942 -1.3154138  -1.26875341]
 [-1.2558755  -1.23844714 -1.25525093 -1.24713926]
 [-1.24495855 -1.20768565 -1.24781193 -1.21029488]
 [-1.20420194 -1.20625488 -1.22493702 -1.22132995]
 [-1.22139613 -1.22011544 -1.26482863 -1.25780953]
 [-1.2558755  -1.23075677 -1.2679902  -1.23373301]
 [-1.22494414 -1.21036834 -1.22716872 -1.21521962]
 [-1.21857592 -1.20097893 -1.21712608 -1.20710291]]


In [30]:
print(Y)

[[-1.20265537]
 [-1.21948567]
 [-1.19428571]
 ...
 [ 2.01193123]
 [ 2.1265592 ]
 [ 2.07561343]]


In [29]:
print(Sequence_length)

11


In [105]:
np.save("data/mean_10",mean)
np.save("data/std_10",std)

np.save("data/Y",Y)
np.save("data/X",X_sequence)